name: Essential Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.0'

      - name: Install & Test
        run: |
          bun install --frozen-lockfile
          bun run type-check
          bun run test:run
          bun run build
        env:
          V0_API_KEY: test-mock-key-12345
          NODE_ENV: test